CREATE DEFINER=`root`@`localhost` PROCEDURE `createUser`(
  IN  IN_USER_GUID     varchar(32),
  IN  IN_USER_NAME     varchar(15),
  IN  IN_USER_PASSWORD varchar(40),
  IN  IN_USER_EMAIL    varchar(40),
  IN  IN_USER_PHONE    varchar(40),
  OUT OUT_RESULT int
)
BEGIN
    DECLARE D_USER_PATH varchar(100);
    DECLARE D_USER_SPACE_SIZE int;
    DECLARE D_USER_TYPE int;
    DECLARE D_USER_LOGO varchar(255);
    DECLARE D_USER_CREATE_DATE datetime default now();

    set OUT_RESULT=2;

    INSERT INTO user_info (USER_GUID, USER_NAME, USER_PASSWORD, USER_EMAIL, USER_PHONE, USER_PATH, USER_SPACE_SIZE, USER_CREATE_DATE, USER_TYPE)
    VALUES(IN_USER_GUID, IN_USER_NAME, IN_USER_PASSWORD, IN_USER_EMAIL, IN_USER_PHONE, D_USER_PATH, D_USER_SPACE_SIZE, D_USER_CREATE_DATE, D_USER_TYPE);

  END