CREATE DEFINER=`root`@`localhost` PROCEDURE `createUser`(
  IN  IN_USER_GUID     varchar(32),
  IN  IN_USER_NAME     varchar(15),
  IN  IN_USER_PASSWORD varchar(40),
  IN  IN_USER_EMAIL    varchar(40),
  IN  IN_USER_PHONE    varchar(40),
  IN  D_USER_PATH varchar(100),
  OUT OUT_RESULT int
)
BEGIN

    DECLARE D_USER_SPACE_SIZE int default 2;
    DECLARE D_USER_TYPE int default 0;
    DECLARE D_USER_LOGO varchar(255);
    DECLARE D_USER_CREATE_DATE datetime default now();
    DECLARE D_EXIST_ID int default 0;

    DECLARE EXIT HANDLER FOR SQLWARNING,NOT FOUND,SQLEXCEPTION set OUT_RESULT=-1;/*Exception then OUT_RESULT=-1*/
    
    select count(ID) INTO D_EXIST_ID FROM user_info WHERE USER_PHONE = IN_USER_PHONE and USER_NAME = IN_USER_NAME;/*USER_PHONE and USER_NAME both exist then OUT_RESULT=-5*/
    
    if (D_EXIST_ID = 0) then
		SELECT count(ID) INTO D_EXIST_ID FROM user_info WHERE USER_PHONE = IN_USER_PHONE;/*USER_PHONE exist then OUT_RESULT=-2*/
		if (D_EXIST_ID = 0) then
    		SELECT count(ID) INTO D_EXIST_ID FROM user_info WHERE USER_NAME = IN_USER_NAME;/*USER_NAME exist then OUT_RESULT=-3*/
			if (D_EXIST_ID = 0) then
				INSERT INTO user_info (USER_GUID, USER_NAME, USER_PASSWORD, USER_EMAIL, USER_PHONE, USER_PATH, USER_SPACE_SIZE, USER_CREATE_DATE, USER_TYPE)
				VALUES(IN_USER_GUID, IN_USER_NAME, IN_USER_PASSWORD, IN_USER_EMAIL, IN_USER_PHONE, D_USER_PATH, D_USER_SPACE_SIZE, D_USER_CREATE_DATE, D_USER_TYPE);
            
				SELECT ID INTO OUT_RESULT FROM user_info WHERE USER_GUID = IN_USER_GUID;/*Success then OUT_RESULT=ID*/
			else
				set OUT_RESULT=-3;
			end if;
		else
			set OUT_RESULT=-2;
		end if;
    else
		set OUT_RESULT=-5;
    end if;
    
END